### ISSUE TITLE
Remove caching of Via HTML pages

### ISSUE THREAD

**Issue by seanh** [hypothesis/lti#24]
When an HTML annotation assignment is launched the app [caches the Via-proxied copy of the HTML page locally](https://github.com/hypothesis/lti/blob/53118f32c546918b4286b68c4333abdb60a7141b/lti/app.py#L295). These cached copies are never invalidated, which means:

* If the third-party HTML page changes, users annotating the page with the Canvas app will never see the page updates. (On the other hand if the page changes or disappears in a way the teacher _doesn't_ want, users are protected from that. Showing changes is probably the correct behaviour though.)

* If a page has previously been annotated by users from the same course, even if this was a long time ago, and then users from that same course and school annotate the same page as an assignment - they will get the old cached copy of the page from when someone in the class first annotated it.

* If the third-party page has an error the first time someone tries to annotate it (e.g. it fails to render the article) then this error page will be what gets cached by our Canvas app, and it won't be possible to annotate the working page in Canvas.

  (I think if the error causes a non-200 HTTP response from Via then the Canvas app might crash and not cache the page, though. Not sure what status code Via sends when you ask it to proxy a page that doesn't 200 though.)

* Similarly if our caching code messes up and corrupts the file (which I believe it can do) users will forever be served a broken page until we login and clear the cache

* If Via is down or has an error the first time someone tries to annotate it - same problem.

* The number of cached Via responses on the server's filesystem just grows and grows - the available disk space will run out. The cache is never cleared, or older cached pages never rolled out.

* The way it's currently implemented [File caching is incompatible with the multiple app servers](https://github.com/hypothesis/lti/issues/93) that our production environment uses

* The way it's currently being implemented I believe the file caching may be incompatible with a single app server serving multiple requests at once, as simultaneous requests may write to the same cached file and corrupt it

See also:

* [File caching is incompatible with multiple app servers](https://github.com/hypothesis/lti/issues/93)

**Comment by seanh** [comment]
@judell Can you clarify what this caching of Via responses is for? It's just to speed up loading the assignments?

**Comment by chdorner** [comment]
In addition to the shortcomings above, when taking into account how our typical production infrastructure looks like where can run multiple instances at the same time (depending on traffic), and that each deploy will run on a set of new instances, this means that:

* Depending on which instance processes the request, the locally cached via response might be different
* All the cached via responses get invalidated because a deploy is a set of new instances that don't share any sort of file storage.

We basically can't rely on any local file caching the way we run software in a production environment. The biggest question for me is why do we even need to cache these via responses? If the reason is that via is slow, then we should just fix via instead of creating more problems for ourselves by caching via responses.

---

To answer one of @seanh's questions:

> Not sure what status code Via sends when you ask it to proxy a page that doesn't 200 though.

Via proxies the status code as well, like the body and (most) headers. So a 404 status code from an origin request will be returned as a 404 as well.

**Comment by seanh** [comment]
I _think_ it's probably okay that different app servers might return different cached pages, and that all the cached pages get blown away whenever we do a deploy, because these pages are just cached copies. It's certainly undesirable weirdness but we can probably get away with it.

The fact that it might fill up the available local filesystem storage quote might be a problem though?

I don't see any reason for the caching other than slowness, but I'm not sure. So simply getting rid of this caching behaviour may be an option - it'll be slower but the code will be simpler and a bunch of weird / unpredictable / undesirable behaviours will be gone.

Completely agree that we need to replace Via. Or change the Canvas app to not require Via (current Via or replacement Via) at all. It's unlikely that we have time to do that before out intended deadline for getting the Canvas app onto production infra though.

**Comment by seanh** [comment]
Updated the description to reflect that I noticed that the cached pages are cached per Canvas instance (i.e. per school) and per course - so students in a different course or a different school won't see the cached copy of the page from another course / school, each course gets their own cached copy.

**Comment by judell** [comment]
> So simply getting rid of this caching behaviour may be an option 

Absolutely, just do that. The benefits of caching are speed and less strain on via, but caching via responses isn't a good way to achieve either, would be better to improve via. Note that the vast majority of Canvas requests so far have been for PDFs, not web pages.

**Comment by seanh** [comment]
Lowering the priority on this, I do want to remove the caching but it's not strictly necessary to do before we can deploy to production infra.

**Comment by seanh** [comment]
Done by https://github.com/hypothesis/lti/pull/113
