### ISSUE TITLE
Remove caching of PDF files

### ISSUE THREAD

**Issue by seanh** [hypothesis/lti#43]
The app [saves PDF files downloaded from the Canvas API to a directory on the server's local filesystem](https://github.com/hypothesis/lti/blob/d6c4282a3fbd4db27f2ef23d35d7fc17e0993996/lti/app.py#L218). This has many of the same issues as [caching Via responses](https://github.com/hypothesis/lti/issues/24) including:

* Possibly delivering outdated versions of files that have been modified. (I'm not sure if this is actually a problem though - doesn't a user have to re-upload a PDF file to Canvas in order to upload a modified version? And won't that change its Canvas API file ID?)

* The server's disk running out of space (the current caching implementation never deletes old files or controls disk space used by the cache)

* Having potentially private PDF files from Canvas saved on our servers.

  Our caching takes the control of the availability of these files out of the hands of the Canvas admins and users and into our own hands:

   Even if the user deletes the file from Canvas, or a Canvas admin deletes it (e.g. the file contained copyrighted information and should not have been made public) our cached copy remains publicly accessible on the internet (to anyone who knows or guesses the URL).

   Even if the the file was made private by the user in Canvas when they uploaded it in the first place our cached copy is publicly accessible on the internet (to anyone who knows or guesses the URL).

* Different browser requests (from the same user or from different users) seeing different results as different app servers on our production infrastructure each have a separate local filesystem

* The way it's currently implemented [File caching is incompatible with the multiple app servers](https://github.com/hypothesis/lti/issues/93) that our production environment uses

* The way it's currently being implemented I believe the file caching may be incompatible with a single app server serving multiple requests at once, as simultaneous requests may write to the same cached file and corrupt it

* If a bad or corrupted file gets into the cache in one way or another, then it will be served to all users of that assignment, until we log in and clear the cache. The most likely error caused by a bad PDF file in the cache is a client-side one from PDF.js that doesn't get reported to us unless users contact us (see <https://github.com/hypothesis/lti/issues/94>)

See also:

* ["Invalid or corrupted PDF file", "Invalid PDF structure" error message from PDF.js](https://github.com/hypothesis/lti/issues/92), seen by multiple users in production and believed (unproven) to have been caused by corrupted PDF files in the cache

* [File caching is incompatible with multiple app servers](https://github.com/hypothesis/lti/issues/93)

**Comment by seanh** [comment]
@judell Is the caching of PDF file necessary or is it just to speed things up? If possible it would simplify things greatly if we could just remove this caching as we can for the Via HTML response caching.

**Comment by judell** [comment]
Same as with the HTML caching, it is not necessary, and is problematic in various ways, and I'd been meaning to turn it off anyway. 

Another reason to do so, in the case of PDFs, is to avoid making PDFs accessible outside of Canvas (because, e.g. copyright). Currently you can discover LTI URLs like lti.hypothesislabs.com/viewer/web/ef097ba98c9772d0af77121d592862c6.pdf in https://hypothes.is/search.  A non-Canvas users who follows such a link will see "You are not logged in to Canvas" (by way of https://github.com/judell/lti/commit/cbbe4b069c5ecf8b38e6fa0c504d41c013911cf4) but that is obviously not a strong solution, just a discouragement. 

I'm not sure what's the best way to handle the visibility of LTI URLs in /search, what do you think?

**Comment by seanh** [comment]
Lowering the priority on this, I do want to remove the caching but it's not strictly necessary to do before we can deploy to production infra.

**Comment by seanh** [comment]
This was fixed by [having the app use Via for PDF assignments](https://github.com/hypothesis/lti/pull/95). All PDF caching is now gone. HTML assignments are still cached right now though, that needs to be removed too.

**Comment by seanh** [comment]
Re-opening this because [I had to at least temporarily revert the move to Via because it broke the Speed Grader](https://github.com/hypothesis/lti/pull/100).

**Comment by seanh** [comment]
Done by https://github.com/hypothesis/lti/pull/112
