### ISSUE TITLE
Add Docker, Jenkins and Docker Hub integration

### ISSUE THREAD

**Issue by seanh** [hypothesis/lti#58]
Get the app working in Docker, add a `Dockerfile` and docs for running the app in Docker, and Jenkins integration that builds the Docker image and pushes it to Docker Hub on each commit to GitHub master.

**Comment by chdorner** [comment]
Infrastructure setup:

* hypothesis/lti#66
* hypothesis/lti#67
* hypothesis/lti#68
* e565e5f7ee53ceb15c2b5a02fbf6b6f71c77b5c5

Migrations setup:
* hypothesis/lti#69
* e75c526eb216c31df739162e68c60d3cd677c87d
* hypothesis/deployment@7a5d7d6aba1694f0869ad248a5fd01c37b17ddbb
