### ISSUE TITLE
route_url() is returning http routes

### ISSUE THREAD

**Issue by seanh** [hypothesis/lti#71]
This page <https://lti.hypothes.is/config.xml> is an `https` page but the `<blti:launch_url>http://lti.hypothes.is/lti_setup</blti:launch_url>` is rendering as http. Here's the line of code that generates that URL and passes it to the template: <https://github.com/hypothesis/lti/blob/4d78e62490df17c014d886718b88163b1db7bf78/lti/views/config.py#L12>

And here's where the routes are defined: <https://github.com/hypothesis/lti/blob/4d78e62490df17c014d886718b88163b1db7bf78/lti/routes.py>

**Comment by chdorner** [comment]
This is working now, see:

* https://qa-lti.hypothes.is/config.xml
* https://lti.hypothes.is/config.xml

I've had to set up the paster prefix filter like so: d991a18943bcb6f60f041c7d2742f83965a9ba6a
